/** Lightweight food mission labels — kept out of exerciseRoadmapData to speed Today tab. */

export const FOOD_MEALS: Record<string, string[]> = {
  'Eat everything': [
    'Scan your lunch',
    'Scan a balanced plate',
    'Scan today’s main meal',
    'Scan a protein-forward meal',
    'Scan your dinner',
    'Scan a snack with protein',
    'Scan a weekend meal',
  ],
  Vegetarian: [
    'Scan your vegetarian lunch',
    'Scan a vegetarian protein plate',
    'Scan today’s vegetarian meal',
    'Scan vegetarian eggs or dairy protein',
    'Scan a vegetarian dinner',
    'Scan a vegetarian snack',
    'Scan a weekend vegetarian meal',
  ],
  Vegan: [
    'Scan your vegan lunch',
    'Scan a vegan protein bowl',
    'Scan today’s vegan meal',
    'Scan vegan legumes or tofu',
    'Scan a vegan dinner',
    'Scan a vegan snack',
    'Scan a weekend vegan meal',
  ],
  Carnivore: [
    'Scan your carnivore lunch',
    'Scan a meat-forward plate',
    'Scan today’s animal-based meal',
    'Scan eggs, meat, or fish',
    'Scan a carnivore dinner',
    'Scan a meat or egg snack',
    'Scan a weekend carnivore meal',
  ],
  'Gluten-free': [
    'Scan your gluten-free lunch',
    'Scan a gluten-free plate',
    'Scan today’s gluten-free meal',
    'Scan a naturally GF protein',
    'Scan gluten-free dinner',
    'Scan a gluten-free snack',
    'Scan a weekend GF meal',
  ],
  'Dairy-free': [
    'Scan your dairy-free lunch',
    'Scan a dairy-free plate',
    'Scan today’s dairy-free meal',
    'Scan a dairy-free protein',
    'Scan dairy-free dinner',
    'Scan a dairy-free snack',
    'Scan a weekend dairy-free meal',
  ],
  'High protein': [
    'Scan a high-protein lunch',
    'Scan a protein-packed plate',
    'Scan today’s high-protein meal',
    'Scan your protein source',
    'Scan a high-protein dinner',
    'Scan a protein snack',
    'Scan a weekend protein meal',
  ],
  'Low carb': [
    'Scan a low-carb lunch',
    'Scan a low-carb plate',
    'Scan today’s low-carb meal',
    'Scan a protein-and-veg plate',
    'Scan a low-carb dinner',
    'Scan a low-carb snack',
    'Scan a weekend low-carb meal',
  ],
};

export const FOOD_RECIPES: Record<string, string[]> = {
  'Eat everything': [
    'Cook a balanced dinner',
    'Make a 20-minute protein bowl',
    'Prep a simple sheet-pan meal',
    'Cook a high-protein breakfast idea',
    'Make a colourful dinner plate',
    'Prep tomorrow’s lunch',
    'Cook a weekend comfort meal',
  ],
  Vegetarian: [
    'Cook a vegetarian dinner',
    'Make a vegetarian chickpea bowl',
    'Prep a vegetarian sheet-pan meal',
    'Cook a vegetarian breakfast',
    'Make a vegetarian lentil dinner',
    'Prep a vegetarian lunchbox',
    'Cook a weekend vegetarian meal',
  ],
  Vegan: [
    'Cook a vegan dinner',
    'Make a vegan tofu bowl',
    'Prep a vegan sheet-pan meal',
    'Cook a vegan breakfast',
    'Make a vegan lentil dinner',
    'Prep a vegan lunchbox',
    'Cook a weekend vegan meal',
  ],
  Carnivore: [
    'Cook a carnivore dinner',
    'Make a steak or eggs plate',
    'Prep a simple meat sheet-pan meal',
    'Cook eggs and meat breakfast',
    'Make a fish or beef dinner',
    'Prep a meat-forward lunch',
    'Cook a weekend carnivore meal',
  ],
  'Gluten-free': [
    'Cook a gluten-free dinner',
    'Make a rice or potato protein bowl',
    'Prep a gluten-free sheet-pan meal',
    'Cook a gluten-free breakfast',
    'Make a naturally GF dinner',
    'Prep a gluten-free lunch',
    'Cook a weekend gluten-free meal',
  ],
  'Dairy-free': [
    'Cook a dairy-free dinner',
    'Make a dairy-free protein bowl',
    'Prep a dairy-free sheet-pan meal',
    'Cook a dairy-free breakfast',
    'Make a dairy-free dinner plate',
    'Prep a dairy-free lunch',
    'Cook a weekend dairy-free meal',
  ],
  'High protein': [
    'Cook a high-protein dinner',
    'Make a high-protein bowl',
    'Prep a high-protein sheet-pan meal',
    'Cook a high-protein breakfast',
    'Make a high-protein dinner plate',
    'Prep a high-protein lunch',
    'Cook a weekend high-protein meal',
  ],
  'Low carb': [
    'Cook a low-carb dinner',
    'Make a protein-and-veg bowl',
    'Prep a low-carb sheet-pan meal',
    'Cook a low-carb breakfast',
    'Make a low-carb dinner plate',
    'Prep a low-carb lunch',
    'Cook a weekend low-carb meal',
  ],
};
