-- Seed 30 unique exercises with distinct GIFs for Daily Plans library
insert into public.exercise_library (id, title, item_type, tag, subtitle, duration_minutes, rest_minutes, media_url, cue, sort_order)
values
  ('lib-seed-01', 'Shadowboxing Round', 'exercise', 'Boxing • Guided', 'boxing', 8, 2, 'https://static.exercisedb.dev/media/hoXt6wv.gif', 'Hands up, light feet, jab-cross rhythm.', 0),
  ('lib-seed-02', 'Squat Pulses', 'exercise', 'Hiit • Guided', 'hiit', 10, 3, 'https://static.exercisedb.dev/media/75Bgtjy.gif', 'Stay low. Pulse through the bottom of the squat.', 1),
  ('lib-seed-03', '90/90 Hip Switches', 'exercise', 'Flexibility • Guided', 'flexibility', 12, 2, 'https://static.exercisedb.dev/media/u0cNiij.gif', 'Move slowly. Keep both hips square to the floor.', 2),
  ('lib-seed-04', 'Butterfly Stretch', 'exercise', 'Pregnancy • Guided', 'pregnancy', 10, 0, 'https://static.exercisedb.dev/media/0mB6wHO.gif', 'Breathe into the stretch. Soft knees.', 3),
  ('lib-seed-05', 'Reverse Lunges', 'exercise', 'Weight loss • Guided', 'weight loss', 12, 3, 'https://static.exercisedb.dev/media/kMzUs9Y.gif', 'Long stride back. Front knee tracks over toes.', 4),
  ('lib-seed-06', 'Bike Bursts', 'exercise', 'Hiit • Guided', 'hiit', 8, 2, 'https://static.exercisedb.dev/media/H1PESYI.gif', 'Drive the legs. Easy upper body.', 5),
  ('lib-seed-07', 'Back Extension', 'exercise', 'Tone • Guided', 'tone', 10, 2, 'https://static.exercisedb.dev/media/rUXfn3R.gif', 'Squeeze glutes at the top. Do not hyperextend.', 6),
  ('lib-seed-08', 'Book Rows', 'exercise', 'Muscle • Guided', 'muscle', 10, 2, 'https://static.exercisedb.dev/media/fUBheHs.gif', 'Pull elbows back. Soften the shoulders.', 7),
  ('lib-seed-09', 'Bag Front Kicks', 'exercise', 'Karate • Guided', 'karate', 8, 2, 'https://static.exercisedb.dev/media/0br45wL.gif', 'Hips square. Snap the kick and reset.', 8),
  ('lib-seed-10', 'Balance Holds', 'exercise', 'Confidence • Guided', 'confidence', 6, 1, 'https://static.exercisedb.dev/media/01qpYSe.gif', 'Find a still point. Soft gaze.', 9),
  ('lib-seed-11', 'Band Rows', 'exercise', 'Pregnancy • Guided', 'pregnancy', 10, 2, 'https://static.exercisedb.dev/media/TFqbd8t.gif', 'Pull to ribs. Keep elbows close.', 10),
  ('lib-seed-12', 'Goblet Squat', 'exercise', 'Muscle • Guided', 'muscle', 12, 4, 'https://static.exercisedb.dev/media/yn8yg1r.gif', 'Chest up. Sit between the heels.', 11),
  ('lib-seed-13', 'Battle Rope Slams', 'exercise', 'Hiit • Guided', 'hiit', 8, 2, 'https://static.exercisedb.dev/media/oHg8eop.gif', 'Power from the hips. Soft knees.', 12),
  ('lib-seed-14', 'Floor Press', 'exercise', 'Muscle • Guided', 'muscle', 10, 3, 'https://static.exercisedb.dev/media/EIeI8Vf.gif', 'Wrists stacked. Controlled lower.', 13),
  ('lib-seed-15', 'March in Place', 'exercise', 'Weight loss • Guided', 'weight loss', 15, 0, 'https://static.exercisedb.dev/media/ealLwvX.gif', 'Pump the arms. Keep a brisk pace.', 14),
  ('lib-seed-16', 'Bulgarian Split Squat', 'exercise', 'Tone • Guided', 'tone', 12, 3, 'https://static.exercisedb.dev/media/9E25EOx.gif', 'Rear foot elevated. Front knee tracks toes.', 15),
  ('lib-seed-17', 'Burpees', 'exercise', 'Hiit • Guided', 'hiit', 10, 2, 'https://static.exercisedb.dev/media/dK9394r.gif', 'Chest to floor option or step-back.', 16),
  ('lib-seed-18', 'Cable Kickbacks', 'exercise', 'Tone • Guided', 'tone', 10, 2, 'https://static.exercisedb.dev/media/HEJ6DIX.gif', 'Squeeze glute at the top of each rep.', 17),
  ('lib-seed-19', 'Cable Woodchops', 'exercise', 'Tone • Guided', 'tone', 10, 2, 'https://static.exercisedb.dev/media/9pa4H5m.gif', 'Rotate from the ribs. Soft knees.', 18),
  ('lib-seed-20', 'Ankle Rocks', 'exercise', 'Flexibility • Guided', 'flexibility', 8, 0, 'https://static.exercisedb.dev/media/m0tCHqc.gif', 'Slow circles. Keep weight even.', 19),
  ('lib-seed-21', 'Dead Bug Core', 'exercise', 'Hiit • Guided', 'hiit', 8, 1, 'https://static.exercisedb.dev/media/iny3m5y.gif', 'Press lower back into the floor.', 20),
  ('lib-seed-22', 'Curtsy Lunges', 'exercise', 'Tone • Guided', 'tone', 10, 2, 'https://static.exercisedb.dev/media/gUjqdei.gif', 'Cross the back leg behind. Tall chest.', 21),
  ('lib-seed-23', 'Dumbbell Thrusters', 'exercise', 'Weight loss • Guided', 'weight loss', 10, 3, 'https://static.exercisedb.dev/media/yWxMvB5.gif', 'Drive up explosively. Soft landing.', 22),
  ('lib-seed-24', 'Fat-Burn Walk', 'exercise', 'Weight loss • Guided', 'weight loss', 20, 0, 'https://static.exercisedb.dev/media/qPEzJjA.gif', 'Easy conversational pace.', 23),
  ('lib-seed-25', 'Mountain Climbers', 'exercise', 'Hiit • Guided', 'hiit', 8, 2, 'https://static.exercisedb.dev/media/RJgzwny.gif', 'Hips low. Quick feet.', 24),
  ('lib-seed-26', 'Forearm Plank', 'exercise', 'Weight loss • Guided', 'weight loss', 5, 1, 'https://static.exercisedb.dev/media/hCjGsRQ.gif', 'Brace core. Long body line.', 25),
  ('lib-seed-27', 'Hamstring Fold', 'exercise', 'Flexibility • Guided', 'flexibility', 10, 0, 'https://static.exercisedb.dev/media/99rWm7w.gif', 'Hinge from hips. Soft knees.', 26),
  ('lib-seed-28', 'Hip Flexor Stretch', 'exercise', 'Weight loss • Guided', 'weight loss', 8, 0, 'https://static.exercisedb.dev/media/tFGKm99.gif', 'Tuck pelvis. Feel the front of the hip open.', 27),
  ('lib-seed-29', 'Hip Thrust', 'exercise', 'Muscle • Guided', 'muscle', 12, 3, 'https://static.exercisedb.dev/media/Pjbc0Kt.gif', 'Drive through heels. Squeeze at the top.', 28),
  ('lib-seed-30', 'Incline Walk', 'exercise', 'Weight loss • Guided', 'weight loss', 15, 0, 'https://static.exercisedb.dev/media/rjiM4L3.gif', 'Slight incline. Steady cadence.', 29)
on conflict (id) do update set
  title = excluded.title,
  item_type = excluded.item_type,
  tag = excluded.tag,
  subtitle = excluded.subtitle,
  duration_minutes = excluded.duration_minutes,
  rest_minutes = excluded.rest_minutes,
  media_url = excluded.media_url,
  cue = excluded.cue,
  sort_order = excluded.sort_order,
  status = 'published',
  updated_at = now();
